### ISSUE TITLE
Broken links/css in readthedocs 404 page 

### ISSUE THREAD

**Issue by brianhlin** [mkdocs/mkdocs#1317]
The [404.html](https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/404.html) added in 0.17.0 seems to have broken links and css ([failing CI build](https://travis-ci.org/opensciencegrid/docs/builds/290469999?utm_source=github_status&utm_medium=notification)). The links in the generated `404.html` file all start with a `docs/...` prefix but when I inspect the `site` dir after a `mkdocs build`, there is no `docs` directory.

**Comment by waylan** [comment]
Hmm, its working fine for me (see [mkdocs.org][1]). I checked the readthedocs theme locally, and it works fine also. So I looked at your project.

Then I noticed that you have `site_url: https://opensciencegrid.github.io/docs` set in your [config file][2]. As the 404 page could be shown for any URL, it can't use relative URLS. Therefore, it uses `site_url` to derive an absolute URL. In your case, it takes `/docs` from the `site_url` setting and prepends it to the URL of each link on the page. Of course, when running the dev server locally, that shouldn't apply.

At the time that we implemented the absolute URLs that way, the dev server didn't have support for returning a 404 page (just a simple plain-text message), so we weren't concerned that it didn't work there as it does on the production server. Since then, we got 404 support added to the dev server and presumably forgot about that detail.

Thanks for the report. We'll need to fix this. However, be aware that while your patch (via a custom 404 template) appears to resolve the problem in the dev server, it will have broken things on the production server if/when you deploy it. I would recommend removing it and enduring the broken dev server until we fix this in 0.17.1 (I hope). 

[1]: http://www.mkdocs.org/foo
[2]: https://github.com/opensciencegrid/docs/blob/master/mkdocs.yml#L2

**Comment by brianhlin** [comment]
Thanks for the quick reply! The custom 404 seems to be working in production (https://opensciencegrid.github.io/docs/site-planning/s) so we'll probably just keep things this way until this is fixed.

**Comment by brianhlin** [comment]
I hadn't bothered to push the change to production, previously. I tested it on my [own fork](https://brianhlin.github.io/docs/s) and it looks like you're right, it works in production.

**Comment by waylan** [comment]
I just pushed a fix for this in #1318. As this effects the dev server only, we'll wait to see if any more bugs surface before doing a release. Either way, this will be fixed in the 0.17.1 release when it comes out. Thanks again for the report.

**Comment by brianhlin** [comment]
This still appears to be broken for 1.17.1 ([failing CI](https://travis-ci.org/opensciencegrid/management/builds/308693780#L563-L567)):

```
URL        `/management/img/favicon.ico'
Parent URL file:///home/travis/build/opensciencegrid/management/site/404.html, line 10, col 3
Real URL   file:///management/img/favicon.ico
Check time 0.000 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/management/img/favicon.ico'>
```

**Comment by waylan** [comment]
So the fix for this issue was specifically related to the dev server. However, your errors are all related to `file://` URLs, which is a completely different animal. For example, consider the quoted error you provide above. The URL is `/management/img/favicon.ico`. From a server, that would work correctly as `/management` is at the server root, However, for a `file://` based URL, that would only work if the `management` dir is at the root of your file system. Of course its not. I'm assuming from your CI logs that its actually at  `/home/travis/build/opensciencegrid/management`.

Using the `file://` scheme means that each build on each system would be completely different. Even builds at different locations on the same system would be different. Therefore, we don't officially support building a site to be used with the `file://` scheme. Sure, for the most part you can browse the site (because we use relative URLs everywhere we can), but search and error pages don't work (because we need absolute URLs there). Of course without a server to intercept a request for a missing page, error pages are pointless, so we will never support error pages with the `file://` scheme. We do intend to get search working with the `file://` scheme in an upcoming refactor of search, but that is a separate issue.

So I was curious why we don't hit the same error for MkDoc's linkchecker tests and I don't see any linkchecker config in your repo. However, the Travis log [indicates][1] you are calling linkchecker like this: `linkchecker --config=ci/linkchecker.config site/index.html`. But we already established that your server root is `/management`, so that needs to be passed to linkchecker. In fact, [MkDocs][2] passes the absolute path to the server root to linkchecker (`linkchecker {envtmpdir}/builds/`). Of course, we have the `envtmpdir` variable which get proper expanded because we're using tox, but you would need to effectively do the same thing. In other words, this is a configuration error on your part. You need to go through some gymnastics to make linkchecker work without your site behind a server. Or possibly, you could have it skip the error page.

[1]: https://travis-ci.org/opensciencegrid/management/builds/308693780#L551
[2]: https://github.com/mkdocs/mkdocs/blob/master/tox.ini#L35

**Comment by brianhlin** [comment]
Sorry, I don't see how it's a configuration. It still strikes me as brokenness in `404.html`. Note that I'm running `mkdocs build`, which by default is building into `site/`, relative to my local repository:

```
$ PYTHONPATH=src mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/blin/docs/management/site 
```

Do you really need absolute URLs for search and error pages? Because the root `index.html` seems to be using relative URLs:

```
$ pwd
/home/blin/docs/management
$ grep search.js site/index.html 
      <script src="./search/search.js"></script>
```

Doing the same check on `404.html`, however, shows an incorrect absolute path.

```
$ grep search.js site/404.html 
      <script src="/management/search/search.js"></script>
```

**Comment by waylan** [comment]
> Do you really need absolute URLs for search and error pages?

Yes, absolute URLs are really necessary for error pages, as explained [here][1] (which was also linked above). True, absolute URLs are not necessary for search, but a fix for that is in the works (unfortunately, the way search is currently implemented that fix needs to be a complete refactor of the relevant JS). 

> Note that I'm running `mkdocs build`, which by default is building into `site/`, relative to my local repository.

Yes, but you have `site_url: https://opensciencegrid.github.io/management/` in your config, so the absolute path to the home page is `/management/`, not `/`. The fix we applied causes the `site_url` setting to be ignored when running the dev sever (so the absolute path to the home page is  `/`). But you're not running the dev server so that setting is not getting ignored. Normally that would be fine. The one exception is if you are using the `file://` scheme. And we don't care if error pages don't work with the `file://` scheme because they are pointless in that context. 

In other words, the mkdocs config (the absolute path to the home page being `/management/`) does not match your testing environment. Either you need to make your test environment match your config, or your config match your test environment.

So you have a few options:

1. Run a server and have linkchecker run against that server.
2. Build without `/management/` in your `site_url`.
3. Adjust your test config to account for the absolute URLs in the error page (and search until the refactor is completed) having a root of `/management`.
4. Configure linkchecker to ignore the error page (and search...).


Ideally, I would prefer option 1 (as the test environment would match the production environment), but you then need to get Travis to shut the server down after the test completes, and I'm not sure how to get that to work. Option 2 is not possible via the `build` command (there's no `--site_dir` flag), so you would need to modify `mkdocs.yml` (perhaps via a script?), which is less than ideal. That leaves options 3 & 4, which I previously suggested, 

[1]: https://github.com/mkdocs/mkdocs/issues/77#issuecomment-242777289

**Comment by waylan** [comment]
Oh one more note: The reason we don't encounter this problem in MkDocs' tests is that we have `site_url: http://mkdocs.org/` so our server root is `/`. This problem only exists when the server root in `site_url` is something other than `/` and you use the `file://` scheme. But that is a different (albeit related) issue than reported here. The reported issue here is about the dev server, which was fixed.

**Comment by brianhlin** [comment]
The issue I [originaly reported](https://github.com/mkdocs/mkdocs/issues/1317#issue-267207369) was actually concerning [mkdocs build](https://travis-ci.org/opensciencegrid/docs/builds/290469999#L548). I was just under the impression that your fix for the dev server would address the issue in `mkdocs build` as well but I see now why it wouldn't. Thanks for the thorough explanation.
