### ISSUE TITLE
H3 and H4 TOC items appear to be at the same level in the ReadTheDocs theme.

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#278]
Mentioned as a side point in #256.

It would be better if we can make the different levels clearer. Perhaps by just further indentation.

**Comment by d0ugal** [comment]
This was fixed some time ago, I can't find the relevant link now.

**Comment by sahilTakiar** [comment]
Can anyone confirm this is no longer an issue? I am still hitting this behavior. All headers within a `.md` file appear on the same level in the TOC. 

It would be nice if the TOC behaved as in the `readthedocs` docs: https://docs.readthedocs.org/en/latest/getting_started.html#in-markdown

A `+` and `-` toggle expanding / collapsing the TOC. Is that possible?

**Comment by sahilTakiar** [comment]
I believe the issue I am facing will be fixed with: https://github.com/mkdocs/mkdocs/issues/588? Just want to confirm so that I know what issue to track. Thanks.

**Comment by Xemiru** [comment]
@sahilTakiar The issue still persist, but you can work around it by surrounding the header with header tags instead of markdown tags.

That is, 
```
# Test
```

becomes

```
<h1>Test</h1>
```

**Comment by sahilTakiar** [comment]
Thanks @Xemiru!

**Comment by Xemiru** [comment]
@sahilTakiar Another thing I figured out is that it seems to be caused by the TOC extension. The headers get locked to the last value you set `baseLevel` to, even if you completely remove the setting. Setting it back to the default value (think it was 1) made headers go back to normal, in my case.
