### ISSUE TITLE
mkdocs serve 404 error: fonts/fontawesome-webfont.woff2

### ISSUE THREAD

**Issue by sinkcup** [mkdocs/mkdocs#894]
```
mkdocs --version
  mkdocs, version 0.15.3
mkdocs serve
```

open http://127.0.0.1:8000/, it will be a error:

```
404 GET /fonts/fontawesome-webfont.woff2?v=4.5.0
```

screenshot:
![2016-04-14 14-07-00](https://cloud.githubusercontent.com/assets/4971414/14518417/39752e44-024a-11e6-8b4f-0f1d3def19e8.png)

![2016-04-14 14-04-52](https://cloud.githubusercontent.com/assets/4971414/14518405/15db0418-024a-11e6-9450-3db91350ec49.png)

**Comment by waylan** [comment]
Curious, how did you install MkDocs? I ask because I'm wondering if we are missing the web font file in the distribution.

**Comment by sinkcup** [comment]
I install by:
```
sudo pip install mkdocs
```

**Comment by waylan** [comment]
Sure enough, the woff2 file is not being included in the package.

**Comment by anantshri** [comment]
that's not all in the generated site folder if i run linkchecker here is what i get.

```
URL        `../fonts/glyphicons-halflings-regular.eot'
Parent URL http://127.0.0.1:8000/css/bootstrap-custom.min.css, line 1, col 36239
Real URL   http://127.0.0.1:8000/fonts/glyphicons-halflings-regular.eot
Check time 3.413 seconds
Result     Error: 404 File not found

URL        `../fonts/glyphicons-halflings-regular.eot?#iefix'
Parent URL http://127.0.0.1:8000/css/bootstrap-custom.min.css, line 1, col 36292
Real URL   http://127.0.0.1:8000/fonts/glyphicons-halflings-regular.eot#iefix
Check time 3.466 seconds
Result     Error: 404 File not found

URL        `../fonts/glyphicons-halflings-regular.woff'
Parent URL http://127.0.0.1:8000/css/bootstrap-custom.min.css, line 1, col 36376
Real URL   http://127.0.0.1:8000/fonts/glyphicons-halflings-regular.woff
Check time 3.551 seconds
Result     Error: 404 File not found

URL        `../fonts/glyphicons-halflings-regular.ttf'
Parent URL http://127.0.0.1:8000/css/bootstrap-custom.min.css, line 1, col 36441
Real URL   http://127.0.0.1:8000/fonts/glyphicons-halflings-regular.ttf
Check time 3.218 seconds
Result     Error: 404 File not found

URL        `../fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular'
Parent URL http://127.0.0.1:8000/css/bootstrap-custom.min.css, line 1, col 36509
Real URL   http://127.0.0.1:8000/fonts/glyphicons-halflings-regular.svg#glyphicons-halflingsregular
Check time 3.062 seconds
Result     Error: 404 File not found

URL        `../fonts/fontawesome-webfont.woff2?v=4.5.0'
Parent URL http://127.0.0.1:8000/css/font-awesome-4.5.0.css, line 1, col 180
Real URL   http://127.0.0.1:8000/fonts/fontawesome-webfont.woff2?v=4.5.0
Check time 2.962 seconds
Result     Error: 404 File not found
```

Out of these lets exclude fontawesome-webfont.woff2 as its fixed via this pull. what about others they are not even in the repository.

Can you push then in repository and make all of them available.

**Comment by waylan** [comment]
Outside of the woff2 file, all of the rest are from the bootstrap themes, which are in a [separate repo][1]. They will need to be addressed there.

[1]: https://github.com/mkdocs/mkdocs-bootstrap

**Comment by anantshri** [comment]
@waylan thanks for the quick pointer. issue raised in correct repository.

**Comment by seaneble** [comment]
I still encounter this. I installed via pip only today, so I assume I have the latest version. Is there something wrong with my installation or did the code not yet get pushed out?

**Comment by waylan** [comment]
The most recent release is 0.15.3, the version this was reported in. This will be fixed in the next release (0.16.0).

**Comment by seaneble** [comment]
Ah, perfect. Thanks and have a nice weekend 👍

**Comment by lokenx** [comment]
I probably commented in the wrong repo, see below! Is there a reason there's no new release with all the changes pushed since 0.15.3?

https://github.com/mkdocs/mkdocs-bootstrap/issues/6#issuecomment-244786058

**Comment by waylan** [comment]
@lokenx see #907 for the status of 0.16.
